### PR TITLE
Bump Tracy to get sample_max_stack kernel version check

### PR DESCRIPTION
**Pull request by sisuresh**
# Description

https://github.com/stellar/tracy/commit/d48b3187b11b3457a9d060e045285c96b9fda49b introduced a bug where Tracy would fail to compile on Linux kernel versions < 4.8. This broke our Jenkins package builder job with the error `../lib/tracy/client/TracySysTrace.cpp:651:8: error: no member named 'sample_max_stack' in 'perf_event_attr'
    pe.sample_max_stack = 127;` 

A bug fix for this was introduced here https://github.com/stellar/tracy/commit/24c834bf8cb8d89d5361fa9c26109ba679bbc5a2, which is the commit this PR bumps Tracy to.

# Checklist
- [ ] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [ ] Rebased on top of master (no merge commits)
- [ ] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [ ] Compiles
- [ ] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
r+ 159020c36277e510130cb49e63e89d44ea7ef6c6
