### ISSUE TITLE
Can't build stellar-core v17.0.0 on Ubuntu 16.04 (xenial)

### ISSUE THREAD

**Issue by gituser** [stellar/stellar-core#3037]
## Issue Description

*Describe your bug/feature request in detail.*

It seems `stellar-core v17.0.0` no longer builds on Ubuntu 16.04 (xenial)

```
In file included from xdrc/parse.yy:4:
In file included from ./xdrc/xdrc_internal.h:10:
In file included from /usr/include/c++/v1/unordered_map:369:
/usr/include/c++/v1/__hash_table:1132:43: error: conflicting types for '__hash_table<_Tp, _Hash, _Equal, _Alloc>'
__hash_table<_Tp, _Hash, _Equal, _Alloc>::__hash_table()
                                          ^
/usr/include/c++/v1/__hash_table:839:5: note: previous declaration is here
    __hash_table()
    ^
/usr/include/c++/v1/__hash_table:1200:43: error: conflicting types for '__hash_table<_Tp, _Hash, _Equal, _Alloc>'
__hash_table<_Tp, _Hash, _Equal, _Alloc>::__hash_table(__hash_table&& __u)
                                          ^
/usr/include/c++/v1/__hash_table:853:5: note: previous declaration is here
    __hash_table(__hash_table&& __u)
    ^
In file included from xdrc/scan.ll:4:
In file included from ./xdrc/xdrc_internal.h:10:
In file included from /usr/include/c++/v1/unordered_map:369:
/usr/include/c++/v1/__hash_table:1132:43: error: conflicting types for '__hash_table<_Tp, _Hash, _Equal, _Alloc>'
__hash_table<_Tp, _Hash, _Equal, _Alloc>::__hash_table()
                                          ^
/usr/include/c++/v1/__hash_table:839:5: note: previous declaration is here
    __hash_table()
    ^
/usr/include/c++/v1/__hash_table:1200:43: error: conflicting types for '__hash_table<_Tp, _Hash, _Equal, _Alloc>'
__hash_table<_Tp, _Hash, _Equal, _Alloc>::__hash_table(__hash_table&& __u)
                                          ^
/usr/include/c++/v1/__hash_table:853:5: note: previous declaration is here
    __hash_table(__hash_table&& __u)
    ^
In file included from xdrc/gen_server.cc:2:
In file included from xdrc/xdrc_internal.h:10:
In file included from /usr/include/c++/v1/unordered_map:369:
/usr/include/c++/v1/__hash_table:1132:43: error: conflicting types for '__hash_table<_Tp, _Hash, _Equal, _Alloc>'
__hash_table<_Tp, _Hash, _Equal, _Alloc>::__hash_table()
                                          ^
/usr/include/c++/v1/__hash_table:839:5: note: previous declaration is here
    __hash_table()
    ^
/usr/include/c++/v1/__hash_table:1200:43: error: conflicting types for '__hash_table<_Tp, _Hash, _Equal, _Alloc>'
__hash_table<_Tp, _Hash, _Equal, _Alloc>::__hash_table(__hash_table&& __u)
                                          ^
/usr/include/c++/v1/__hash_table:853:5: note: previous declaration is here
    __hash_table(__hash_table&& __u)
    ^
2 errors generated.

```

### stellar-core 
`stellar-core v17.0.0`

### Environment
* Operation System & Version (You can usually obtain from `uname -a`)
Ubuntu 16.04.7 LTS (xenial)

* Are you running from the command line? From a container?
Building from source

* Did you pass in special parameters when building the app?
* Please add any additional relevant configuration related to this bug report.

## Supporting Files

Here is a script I'm using to build stellar-core:
```
#!/bin/bash
#VER=$(git describe --tags)
daemon=$(pname=$(pwd); echo ${pname##/*/})

git submodule init
git submodule update

export CXX=clang++-8
export CC=clang-8
export CFLAGS="-O3 -g1 -fno-omit-frame-pointer"
export CXXFLAGS="$CFLAGS -stdlib=libc++ -isystem /usr/include/libcxxabi"
make clean

./autogen.sh 
./configure

if [ "$?" != 0 ]; then
   echo "[-] configure failed"
   exit 1
fi

make -j$(nproc)
if [ "$?" == 0 ]; then
  echo "Build OK!"
else
  echo "Build Failed!"
fi
```

**Comment by graydon** [comment]
Unfortunately v17.0.0 [no longer supports Ubuntu 16.04 LTS](https://github.com/stellar/stellar-core/commit/f8d6a90d38701662159343710fb99285a665b025).

18.04 and 20.04 are supported. The specific issue you seem to be encountering is likely the lack of a C++17-supporting compiler, which you may be able to work around by installing a newer version of clang, if you can find (or build) one packaged for 16.04.

However, SDF is not presently building packages or testing on 16.04 anymore, so it is likely that other incompatibilities or build-breaking issues will occur. We're happy to accept minor / non-intrusive fixes for these if you want to preserve compatibility further, but not major changes (eg. we are not likely to be reverting C++17 usage in the codebase).

**Comment by graydon** [comment]
Apologies -- I didn't notice that your build script is using clang 8 already, and doing a clean reconfigure -- this _should_ probably still work; perhaps there is some stale state in your repository?

I just built successfully using your script from a fresh checkout in an ubuntu 16.04 container, and it still seems to build ok. Could you try from a fresh checkout?

**Comment by gituser** [comment]
@graydon, no, I don't have any stale files, I even cleaned everything (including submodules) and that still didn't help - still same error.

Did you install custom toolchain inside your ubuntu 16.04 container?

**Comment by graydon** [comment]
Yes, I installed clang-8 from the [testing toolchains repo](https://github.com/stellar/stellar-core/blob/master/INSTALL.md#adding-the-test-toolchain-optional). I assumed you did too as your script uses clang-8, which is not available on stock ubuntu 16.04.

**Comment by gituser** [comment]
@graydon 

No I don't want to install that toolchain as I will need to install it everywhere I use the binaries generated with this gcc and also it's a test toolchain not a stable one I think.

Guess, it's time to update 18.04 for Stellar..

**Comment by gituser** [comment]
Now I'm facing another issue: can't build `v17.2.0` on Ubuntu 18.04.
Why do you change the toolchain requirement so often and break the compilation?

**Comment by graydon** [comment]
Great! Apologies for the changes -- we've just been trying to migrate the codebase to C++17. It's 2021 and compilers have been shipping support for it for quite a while now.
